### ISSUE TITLE
When will there a new release that fixes the 0.6.1 compilation error?

### ISSUE THREAD

**Issue by ujamshy** [typelift/Swiftz#324]
Hello,

Version 0.6.1 does not compile with XCode 8.2
This has been fixed on the master branch but there was not a new version release.
This causes all frameworks that use carthage and release ~> 0.6.1 to break.

When do you plan to release the next version?

Thanks,
Ury Jamshy.
